version: '3.8'

services:
  frontend:
    build:
      context: ./solid-frontend
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./solid-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host

  backend:
    build: ./backend
    ports:
      - '5001:5001'
    volumes:
      - ./express-backend:/app
      - /app/node_modules
