name: Build and Push Docker Images

on:
  push:
    branches:
      - main # Change si tu bosses sur une autre branche

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Docker Buildx (builder avancé)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build + Push frontend
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./solid-frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/solid-frontend:latest

      # Build + Push backend
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
